language: c
arch: ppc64le
os:
  - linux

compiler:
  - gcc 

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y git tar make gcc g++ wget cmake libboost-all-dev bison flex openjdk-8-jdk maven gperf libsnappy-dev libevent-dev automake libtool libjson-perl libreadline-dev
  - sudo apt-get install -y libapr1 libapr1-dev unzip curl libcurl4-openssl-dev libbz2-dev pkg-config libssl-dev 
  - sudo apt-get install -y libjson-c-dev libxml2-dev python-dev python-setuptools python-pip libghc-gsasl-dev
  - sudo apt-get install -y libgtest-dev gsasl build-essential libprotobuf-dev libkrb5-dev protobuf-compiler
  - sudo pip uninstall pyyaml
  - sudo apt-get install libyaml-dev libpython2.7-dev
  - sudo pip install pyyaml
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-ppc64el
  - cd /
  - sudo wget http://archive.apache.org/dist/thrift/0.10.0/thrift-0.10.0.tar.gz 
  - sudo tar -xvzf thrift-0.10.0.tar.gz
  - cd /
  - sudo wget https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz
  - sudo tar -xvzf protobuf-2.5.0.tar.gz --no-same-owner
  - cd thrift-0.10.0
  - sed -i '98s/1.5/1.6/g' lib/java/build.xml
  - sudo ./configure 
  - sudo make
  - sudo make install
  - cd ..
  

  
  - cd /
  - sudo git clone https://github.com/json-c/json-c.git
  - cd json-c
  - sudo git clean -fd
  - sudo git reset --hard json-c-0.12.1-20160607
  - sudo ./autogen.sh
  - sudo ./configure --build=ppc64le-pc-linux
  - sudo make
  - sudo make install
  - cd ..
  
  
  - cd protobuf-2.5.0
  - sed -i '22s/http:\/\/googletest.googlecode.com\/files\/gtest-1.5.0.tar.bz2/https:\/\/src.fedoraproject.org\/repo\/pkgs\/gtest\/gtest-1.5.0.tar.bz2\/8b2c3c3f26cb53e64a3109d03a97200a\/gtest-1.5.0.tar.bz2/' autogen.sh
  - cd src/google/protobuf/stubs/
  - rm atomicops.h platform_macros.h 
  - sudo wget https://raw.githubusercontent.com/protocolbuffers/protobuf/2.7.0/src/google/protobuf/stubs/atomicops.h 
  - sudo wget https://raw.githubusercontent.com/protocolbuffers/protobuf/2.7.0/src/google/protobuf/stubs/atomicops_internals_power.h  
  - sudo wget https://raw.githubusercontent.com/protocolbuffers/protobuf/2.7.0/src/google/protobuf/stubs/platform_macros.h 
  - cd ../../../../
  - sudo ./autogen.sh
  - sudo ./configure
  - sudo make 
  

  - cd /
  - sudo git clone https://github.com/apache/hawq
  - cd /hawq/depends/libhdfs3/build
  - rm -rf *
  - ../bootstrap
  - make
  - make install 
  - cd /hawq
  - sudo ./configure --build=ppc64le-pc-linux
  - sudo make
  - sudo make install

branches:
  except:
    - legacy
